version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/project
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    container_name: flask_app

#  mysql:
#   image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: flaskdb
#    volumes:
#      - mysql_data:/var/lib/mysql
#volumes:
  #mysql_data