name: auto docker-deploy after push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checking out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setting up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Installing dependencies (installing from requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Running tests (Optional, if you have any tests set up)
      - name: Run tests
        run: |
          python -m unittest discover

      # 5. Authenticating with Google Cloud using the service account key
      - name: Authenticate with GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project devops-451510

      # 6. Install the gke-gcloud-auth-plugin
      - name: Install Google Cloud CLI and GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version


      # 7. Set up Kubernetes authentication
      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials flask-cluster --zone us-central1-a --project devops-451510
          kubectl config use-context gke_devops-451510_us-central1-a_flask-cluster

      # 8. Building Docker image and pushing to Artifact Registry
      - name: Build and push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t us-central1-docker.pkg.dev/devops-451510/my-docker-repo/project-flask-app:latest .
          docker push us-central1-docker.pkg.dev/devops-451510/my-docker-repo/project-flask-app:latest

      # 9. Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/flask-app-deployment flask-app=us-central1-docker.pkg.dev/devops-451510/my-docker-repo/project-flask-app:latest
          kubectl scale deployment flask-app-deployment --replicas=3
